/** API error codes returned in normalized error responses. */
export const ApiErrorCodes = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  ORGANIZATION_SLUG_ALREADY_EXISTS: 'ORGANIZATION_SLUG_ALREADY_EXISTS',
  MULTIPLE_ORGANIZATIONS_REQUIRED: 'MULTIPLE_ORGANIZATIONS_REQUIRED',
  MEMBERSHIP_INACTIVE: 'MEMBERSHIP_INACTIVE',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_ACCESS_DENIED: 'SESSION_ACCESS_DENIED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  ROLE_FORBIDDEN: 'ROLE_FORBIDDEN',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  PRISMA_ERROR: 'PRISMA_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
} as const;

export type ApiErrorCode = (typeof ApiErrorCodes)[keyof typeof ApiErrorCodes];
